apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-ci-cd
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/smtekvn/flask-ci-cd-demo.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
